name: Deploy docs

on:
  push:
    branchs:
      - main

jobs:
  buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkou
        uses: actions/checkout@v2
    
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - run: npm ci

      - run: npm run build

      - name: Deploy Storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}